# Generated by Django 2.1.3 on 2018-12-09 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(null=True)),
                ('paid', models.IntegerField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('paid', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Investment')),
            ],
        ),
    ]
